# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m2NoyfGi336WidF6FhTJJ3qqhTs_NQC-
"""

import streamlit as st
import pandas as pd
import plotly.express as px

st.set_page_config(page_title="commodity Price Heatmap", layout="wide")

@st.cache_data
def load_data():
    df = pd.read_csv("data/commodity_prices_clean_model.csv")
    df["date"] = pd.to_datetime(df["date"], errors="coerce")

    text_cols = ["commodity_name", "group", "category_map", "sub_category1", "sub_category2"]
    for col in text_cols:
        if col in df.columns:
            df[col] = df[col].astype(str).str.strip()

    return df

df = load_data()

st.title("Heatmap Price Nominal USD Antar Komoditas")
st.markdown(
    "Pilih kategori dan komoditas yang ingin dibandingkan. "
    "Heatmap dihitung dari korelasi `price_nominal_usd` antar `commodity_name` berdasarkan data time series per tanggal."
)

st.sidebar.header("Filter")

# Filter bertingkat
group_options = sorted(df["group"].dropna().unique().tolist())
selected_groups = st.sidebar.multiselect(
    "Pilih group",
    options=group_options,
    default=group_options
)


df_filtered = df.copy()
if selected_groups:
    df_filtered = df_filtered[df_filtered["group"].isin(selected_groups)]

all_commodities = st.sidebar.checkbox("Pilih semua commodity", value=True)

commodity_options = sorted(df_filtered["commodity_name"].dropna().unique().tolist())

selected_commodities = st.sidebar.multiselect(
    "Pilih commodity_name",
    options=commodity_options,
    default=commodity_options if all_commodities else []
)

category_map_options = sorted(df_filtered["category_map"].dropna().unique().tolist())
selected_category_map = st.sidebar.multiselect(
    "Pilih category_map",
    options=category_map_options,
    default=category_map_options
)

if selected_category_map:
    df_filtered = df_filtered[df_filtered["category_map"].isin(selected_category_map)]

subcat1_options = sorted(df_filtered["sub_category1"].dropna().unique().tolist())
selected_subcat1 = st.sidebar.multiselect(
    "Pilih sub_category1",
    options=subcat1_options,
    default=subcat1_options
)

if selected_subcat1:
    df_filtered = df_filtered[df_filtered["sub_category1"].isin(selected_subcat1)]

subcat2_options = sorted(df_filtered["sub_category2"].dropna().unique().tolist())
selected_subcat2 = st.sidebar.multiselect(
    "Pilih sub_category2",
    options=subcat2_options,
    default=subcat2_options
)

if selected_subcat2:
    df_filtered = df_filtered[df_filtered["sub_category2"].isin(selected_subcat2)]

commodity_options = sorted(df_filtered["commodity_name"].dropna().unique().tolist())
selected_commodities = st.sidebar.multiselect(
    "Pilih commodity_name yang dibandingkan",
    options=commodity_options,
    default=commodity_options[:8] if len(commodity_options) >= 8 else commodity_options
)

if selected_commodities:
    df_filtered = df_filtered[df_filtered["commodity_name"].isin(selected_commodities)]

# Opsi minimum observasi
min_obs = st.sidebar.slider(
    "Minimum jumlah observasi per commodity",
    min_value=12,
    max_value=200,
    value=24,
    step=12
)

# Ringkasan
st.subheader("Ringkasan Filter")
c1, c2, c3 = st.columns(3)
c1.metric("Rows", len(df_filtered))
c2.metric("Commodity terpilih", df_filtered["commodity_name"].nunique())
c3.metric("Tanggal unik", df_filtered["date"].nunique())

with st.expander("Preview data"):
    st.dataframe(
        df_filtered[["date", "commodity_name", "group", "category_map", "sub_category1", "sub_category2", "price_nominal_usd"]]
        .sort_values(["date", "commodity_name"])
        .head(50),
        use_container_width=True
    )

# Siapkan matrix date x commodity
pivot_df = df_filtered.pivot_table(
    index="date",
    columns="commodity_name",
    values="price_nominal_usd",
    aggfunc="mean"
)

# Buang commodity yang observasinya terlalu sedikit
valid_cols = pivot_df.count()[pivot_df.count() >= min_obs].index.tolist()
pivot_df = pivot_df[valid_cols]

if pivot_df.shape[1] < 2:
    st.warning("Pilih minimal 2 commodity dengan data yang cukup untuk membuat heatmap.")
else:
    corr_matrix = pivot_df.corr(method="pearson")

    st.subheader("Heatmap Korelasi Price Nominal USD Antar Komoditas")
    fig = px.imshow(
        corr_matrix,
        text_auto=".2f",
        color_continuous_scale="RdBu_r",
        zmin=-1,
        zmax=1,
        aspect="auto",
        title="Korelasi Antar Commodity berdasarkan Price Nominal USD"
    )

    fig.update_layout(
        height=800,
        xaxis_title="Commodity Name",
        yaxis_title="Commodity Name",
        coloraxis_colorbar_title="Correlation"
    )

    st.plotly_chart(fig, use_container_width=True)

    st.subheader("Matriks Korelasi")
    st.dataframe(corr_matrix.round(3), use_container_width=True)

    st.subheader("Jumlah Observasi per Commodity")
    obs_df = pivot_df.count().reset_index()
    obs_df.columns = ["commodity_name", "n_observations"]
    obs_df = obs_df.sort_values("n_observations", ascending=False)

    st.dataframe(obs_df, use_container_width=True)
